import ctypes

class T_CAUStatus:
    T_CAUStatus_RuntimeClosed = ctypes.c_uint16(0)
    T_CAUStatus_Closed = ctypes.c_uint16(1)
    T_CAUStatus_Open = ctypes.c_uint16(2)
    T_CAUStatus_Fault = ctypes.c_uint16(3)
    T_CAUStatus_FaultClosed = ctypes.c_uint16(4)
    T_CAUStatus_OpenInit = ctypes.c_uint16(5)

class T_Command:
    T_Command_Initialize = ctypes.c_uint16(0)
    T_Command_Acquire = ctypes.c_uint16(1)
    T_Command_Replay = ctypes.c_uint16(2)
    T_Command_WaitForSamples = ctypes.c_uint16(3)
    T_Command_Update = ctypes.c_uint16(4)
    T_Command_Close = ctypes.c_uint16(5)
    T_Command_Status = ctypes.c_uint16(6)
    T_Command_Function = ctypes.c_uint16(7)
    T_Command_GetFrame = ctypes.c_uint16(8)
    T_Command_Finish = ctypes.c_uint16(9)
    T_Command_FunctionResult = ctypes.c_uint16(10)
    T_Command_Spectrum = ctypes.c_uint16(11)
    T_Command_CAUInfo = ctypes.c_uint16(12)
    T_Command_ReplayFrame = ctypes.c_uint16(13)

class T_FunctionCommand:
    T_FunctionCommand_GetID = ctypes.c_uint16(0)
    T_FunctionCommand_GetFirmwareVer = ctypes.c_uint16(1)
    T_FunctionCommand_GetDriverVer = ctypes.c_uint16(2)
    T_FunctionCommand_GetResolution = ctypes.c_uint16(3)
    T_FunctionCommand_GetFrameLength = ctypes.c_uint16(4)
    T_FunctionCommand_GetTemperature = ctypes.c_uint16(5)
    T_FunctionCommand_StartLinkSend = ctypes.c_uint16(6)
    T_FunctionCommand_SendLinkData = ctypes.c_uint16(7)
    T_FunctionCommand_ReadLinkData = ctypes.c_uint16(8)
    T_FunctionCommand_ActiveMessage = ctypes.c_uint16(9)
    T_FunctionCommand_Calibrate = ctypes.c_uint16(10)
    T_FunctionCommand_SetCalRef = ctypes.c_uint16(11)
    T_FunctionCommand_SamplingStatus = ctypes.c_uint16(12)
    T_FunctionCommand_TfOrDTCapture = ctypes.c_uint16(13)
    T_FunctionCommand_SigDC = ctypes.c_uint16(14)
    T_FunctionCommand_SigRMS = ctypes.c_uint16(15)
    T_FunctionCommand_SigMax = ctypes.c_uint16(16)
    T_FunctionCommand_SigMin = ctypes.c_uint16(17)
    T_FunctionCommand_SigPkPk = ctypes.c_uint16(18)
    T_FunctionCommand_SigStdDev = ctypes.c_uint16(19)
    T_FunctionCommand_SigFreq = ctypes.c_uint16(20)
    T_FunctionCommand_SigAmplitude = ctypes.c_uint16(21)
    T_FunctionCommand_SigPulseFrequency = ctypes.c_uint16(22)
    T_FunctionCommand_SigDutyCycle = ctypes.c_uint16(23)
    T_FunctionCommand_SigPulsePeriod = ctypes.c_uint16(24)
    T_FunctionCommand_SigPulseLength = ctypes.c_uint16(25)
    T_FunctionCommand_SigRiseTime = ctypes.c_uint16(26)
    T_FunctionCommand_SigFallTime = ctypes.c_uint16(27)
    T_FunctionCommand_Sig1Level = ctypes.c_uint16(28)
    T_FunctionCommand_Sig0Level = ctypes.c_uint16(29)
    T_FunctionCommand_SigVSwing = ctypes.c_uint16(30)
    T_FunctionCommand_SigOvershoot = ctypes.c_uint16(31)
    T_FunctionCommand_SigSlewRate = ctypes.c_uint16(32)
    T_FunctionCommand_SigFreq2ndHarmonic = ctypes.c_uint16(33)
    T_FunctionCommand_SigAmp2ndHarmonic = ctypes.c_uint16(34)
    T_FunctionCommand_SigFreq3rdHarmonic = ctypes.c_uint16(35)
    T_FunctionCommand_SigAmp3ndHarmonic = ctypes.c_uint16(36)
    T_FunctionCommand_SigSinad = ctypes.c_uint16(37)
    T_FunctionCommand_SigTHD = ctypes.c_uint16(38)
    T_FunctionCommand_SigHD23 = ctypes.c_uint16(39)

class T_LinkMasterSlave:
    T_LinkMasterSlave_Unlinked = ctypes.c_uint8(0)
    T_LinkMasterSlave_Master = ctypes.c_uint8(1)
    T_LinkMasterSlave_Slave = ctypes.c_uint8(2)

class T_TriggeringUnit:
    T_TriggeringUnit_UnitA = ctypes.c_uint32(0)
    T_TriggeringUnit_UnitB = ctypes.c_uint32(1)